name: task_manager_app
description: A task management app built with Flutter and Provider.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  uuid: ^3.0.7
  # Add other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets, uncomment the following lines:
  # assets:
  #   - assets/
